packages/ella/src/dom/index.ts, packages/ella/src/general/index.ts
isEmpty(window) replaced with typeof window === 'undefined'. Similarly, added navigator object check
=> isEmpty replaced with typof if condition

packages/ella/src/general/index.ts
=> ella asyncThrottle added

packages/ella/package.json, packages/ella/src/dom/index.ts, packages/ella/src/utils/constants/index.ts
adds a function to ella
ella
- [ x ] New feature (non-breaking change which adds functionality)
ella 0.1.2
- [ x ] These changes have been thoroughly tested.
- [ x ] Changes need to be immediately published on npm.
=> forceFocusAndOpenKeyboard

packages/ella/src/general/index.ts
- [X ] Bugfix (non-breaking change which fixes an issue)
- [ X] Changes need to be immediately published on npm.
=> replaceAl replaced

package-lock.json, packages/eslint-config/eslintrc.json, packages/eslint-config/package.json
Added rules of hook in groww-tech eslint config
eslint-config
eslint-config 1.0.4
=> feat: added rules of hooks

packages/ella/package.json, packages/ella/src/number/index.ts, packages/ella/src/string/index.ts
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] These changes have been thoroughly tested.
- [ x ] Changes need to be immediately published on npm.
=> definition of convertPaisaToRupee-and-convertToSentenceCase changed

packages/ella/package.json, packages/ella/src/date/index.ts
Fixes an issue related to dayjs types
ella
0.1.8
=> fix dayjs issue

packages/ui-toolkit/package.json, packages/ui-toolkit/src/components/atoms/Select/Select.tsx, packages/ui-toolkit/src/components/atoms/TextArea/TextArea.tsx, packages/ui-toolkit/src/components/atoms/TextInput/TextInput.tsx
onChange fixes in ui-toolkit
ui-toolkit
=> fix: input

packages/ui-toolkit/package.json, packages/ui-toolkit/src/components/atoms/TextArea/TextArea.tsx
Fixes Props for textarea
ui-toolkit
changed types
- [ x ] Bugfix (non-breaking change which fixes an issue)
0.2.2
- [ x ] These changes have been thoroughly tested.
- [ x ] Changes need to be immediately published on npm.
=> fixed textarea props

packages/ella/src/general/index.ts
Add helper method in `src/general` to check if an object has all 0 values.
Browser support looks good for `.every` method on **Can I use?** [here](https://caniuse.com/?search=every)
=> feat(general): add helper to check if all values are 0 in obj

packages/ella/package.json
Version bump from `ella:v0.1.8 => v0.2.0` to release [PR-94](https://github.com/Groww/webster/pull/94)
=> feat(ella): bump version 0.1.8 => 0.2.0

packages/ui-toolkit/package.json, packages/ui-toolkit/src/components/atoms/LaserBeam/LaserBeam.tsx
fix: Laserbeam Extra props passed
ui-toolkit
=> fix: Laserbeam remove extra props

packages/ella/package.json, packages/ella/src/dom/index.ts
added function for browserVersion
ella
=> feat: added function get_browser_version

packages/ella/package.json, packages/ella/src/general/index.ts
Remove all null properties from an object
Ella
- [x ] New feature (non-breaking change which adds functionality)
Ella 
- [x ] These changes have been thoroughly tested.
=> Remove all null properties from an object

packages/ella/package.json
=> version decreased

packages/ui-toolkit/package.json, packages/ui-toolkit/src/components/atoms/Button/button.css
Button  - primary CTA text color change from primaryBg to constantWhite
ui-toolkit
ui-toolkit - 0.2.4
=> fix: change text color for primary button to constantWhite

packages/ella/package.json, packages/ella/src/general/index.ts
removeNullProperties function updated without mutating the current object
- [X ] These changes have been thoroughly tested.
- [ X] Changes need to be immediately published on npm.
=> updated removeNullProperties function without mutating the current object

.github/workflows/codeql-analysis.yml
This will set up a JS code scanning for our repo
None
Security Enhancement
None
=> Create codeql-analysis.yml file for code scanning

packages/ui-toolkit/src/components/atoms/InformationBoard/InformationBox.tsx
Fixed the issue for component Information box informationBoxClass prop was not working as expected
ui-toolkit
fixes
=> fix: updated cn for parentDivClass

packages/ui-toolkit/src/components/atoms/InformationBoard/informationBox.css
Fixed the icon component getting shrunk on small resolution. 
ui-toolkit
fixes
=> fix: add flex-shrink for icon
